version: '3'

services:
  api:
    build: .
    environment:
      - API_MONGO_URI=db:27017
      - FLASK_APP=api.py
    command: python api.py
    depends_on:
      - db
#    ports:
#      - 5000:5000
    volumes:
      - .:/code
    links:
      - db

  db:
    image: mongo:3.4-jessie
    ports:
      - 27017:27017
    volumes:
      - /home/amcom/data_mongo04jan2018:/data/db

networks:
  default:
    external:
      name: pratoaberto