version: '3'

services:
  web:
    build: .
    environment:
      - API_MONGO_URI=db:27017
      - FLASK_APP=api.py
    command: python -m flask run
    depends_on:
      - db
      - mongo-seed
    ports:
      - 5000:5000
    volumes:
      - .:/code
    links:
      - db

  db:
    image: mongo
    ports:
      - 27017:27017

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - db
    links:
      - db
